# Generated by Django 4.0.4 on 2022-07-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='contacts_en',
            field=models.TextField(null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='bb',
            name='contacts_ru',
            field=models.TextField(null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='bb',
            name='contacts_uk',
            field=models.TextField(null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='bb',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='bb',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='bb',
            name='content_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='bb',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='bb',
            name='created_at_ru',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='bb',
            name='created_at_uk',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='bb',
            name='price_en',
            field=models.FloatField(default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='bb',
            name='price_ru',
            field=models.FloatField(default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='bb',
            name='price_uk',
            field=models.FloatField(default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='bb',
            name='title_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='bb',
            name='title_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='bb',
            name='title_uk',
            field=models.CharField(max_length=40, null=True, verbose_name='Товар'),
        ),
    ]
