# Generated by Django 4.0.4 on 2022-07-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bb_contacts_en_bb_contacts_ru_bb_contacts_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='name_en',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='name_uk',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='Название'),
        ),
    ]
