# Generated by Django 4.0.4 on 2022-08-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rubric_name_en_rubric_name_ru_rubric_name_uk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='contacts_ru',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='created_at_ru',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='price_ru',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='name_ru',
        ),
    ]
