# Generated by Django 4.0.4 on 2022-08-03 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_bb_contacts_ru_remove_bb_content_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalimage',
            options={'verbose_name': 'Додаткове зображення', 'verbose_name_plural': 'Додаткові зображення'},
        ),
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-created_at'], 'verbose_name': 'Оголошення', 'verbose_name_plural': 'Оголошення'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.AddField(
            model_name='comment',
            name='author_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_uk',
            field=models.CharField(max_length=30, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Вміст'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_uk',
            field=models.TextField(null=True, verbose_name='Вміст'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Опубліковано'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at_uk',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bb', verbose_name='Оголошення'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to=main.utilities.get_timestamp_path, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Пройшов активацію?'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Відправляти сповіщення про нові коментарі?'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор оголошення'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='contacts',
            field=models.TextField(verbose_name='Контакти'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='contacts_en',
            field=models.TextField(null=True, verbose_name='Контакти'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='contacts_uk',
            field=models.TextField(null=True, verbose_name='Контакти'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='content_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='created_at_uk',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Виводити в список?'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price_en',
            field=models.FloatField(default=0, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price_uk',
            field=models.FloatField(default=0, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bb', verbose_name='Оголошення'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Вміст'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Виводити на екран?'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name_en',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name_uk',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='Назва'),
        ),
    ]
