# Generated by Django 4.0.4 on 2022-08-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_additionalimage_options_alter_bb_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_uk',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_uk',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at_en',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at_uk',
        ),
    ]
